package no.mhl.twemojiiconsandroid.categories

import no.mhl.twemojiiconsandroid.R
import no.mhl.twemojiiconsandroid.core.model.TwemojiCategory
import no.mhl.twemojiiconsandroid.core.model.TwemojiIcon
import no.mhl.twemojiiconsandroid.core.model.TwemojiSubcategory

internal object FlagsProvider {

    // region All
    fun provideFlags(): List<TwemojiIcon> = listOf(
        provideCountryFlags(),
        provideOthers(),
        provideSubdivisionFlags()
    ).flatten()
    // endregion

    // region Country flags
    fun provideCountryFlags() = listOf(
        TwemojiIcon(plainName = "AscensionIsland", unicode = "1f1e6-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1e8),
        TwemojiIcon(plainName = "Andorra", unicode = "1f1e6-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1e9),
        TwemojiIcon(plainName = "UnitedArabEmirates", unicode = "1f1e6-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1ea),
        TwemojiIcon(plainName = "Afghanistan", unicode = "1f1e6-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1eb),
        TwemojiIcon(plainName = "AntiguaAndBarbuda", unicode = "1f1e6-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1ec),
        TwemojiIcon(plainName = "Anguilla", unicode = "1f1e6-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1ee),
        TwemojiIcon(plainName = "Albania", unicode = "1f1e6-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f1),
        TwemojiIcon(plainName = "Armenia", unicode = "1f1e6-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f2),
        TwemojiIcon(plainName = "Angola", unicode = "1f1e6-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f4),
        TwemojiIcon(plainName = "Antarctica", unicode = "1f1e6-1f1f6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f6),
        TwemojiIcon(plainName = "Argentina", unicode = "1f1e6-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f7),
        TwemojiIcon(plainName = "AmericanSamoa", unicode = "1f1e6-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f8),
        TwemojiIcon(plainName = "Austria", unicode = "1f1e6-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1f9),
        TwemojiIcon(plainName = "Australia", unicode = "1f1e6-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1fa),
        TwemojiIcon(plainName = "Aruba", unicode = "1f1e6-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1fc),
        TwemojiIcon(plainName = "ÅlandIslands", unicode = "1f1e6-1f1fd", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1fd),
        TwemojiIcon(plainName = "Azerbaijan", unicode = "1f1e6-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e6_1f1ff),
        TwemojiIcon(plainName = "BosniaAndHerzegovina", unicode = "1f1e7-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1e6),
        TwemojiIcon(plainName = "Barbados", unicode = "1f1e7-1f1e7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1e7),
        TwemojiIcon(plainName = "Bangladesh", unicode = "1f1e7-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1e9),
        TwemojiIcon(plainName = "Belgium", unicode = "1f1e7-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ea),
        TwemojiIcon(plainName = "BurkinaFaso", unicode = "1f1e7-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1eb),
        TwemojiIcon(plainName = "Bulgaria", unicode = "1f1e7-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ec),
        TwemojiIcon(plainName = "Bahrain", unicode = "1f1e7-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ed),
        TwemojiIcon(plainName = "Burundi", unicode = "1f1e7-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ee),
        TwemojiIcon(plainName = "Benin", unicode = "1f1e7-1f1ef", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ef),
        TwemojiIcon(plainName = "StBarthélemy", unicode = "1f1e7-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f1),
        TwemojiIcon(plainName = "Bermuda", unicode = "1f1e7-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f2),
        TwemojiIcon(plainName = "Brunei", unicode = "1f1e7-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f3),
        TwemojiIcon(plainName = "Bolivia", unicode = "1f1e7-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f4),
        TwemojiIcon(plainName = "CaribbeanNetherlands", unicode = "1f1e7-1f1f6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f6),
        TwemojiIcon(plainName = "Brazil", unicode = "1f1e7-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f7),
        TwemojiIcon(plainName = "Bahamas", unicode = "1f1e7-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f8),
        TwemojiIcon(plainName = "Bhutan", unicode = "1f1e7-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1f9),
        TwemojiIcon(plainName = "BouvetIsland", unicode = "1f1e7-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1fb),
        TwemojiIcon(plainName = "Botswana", unicode = "1f1e7-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1fc),
        TwemojiIcon(plainName = "Belarus", unicode = "1f1e7-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1fe),
        TwemojiIcon(plainName = "Belize", unicode = "1f1e7-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e7_1f1ff),
        TwemojiIcon(plainName = "Canada", unicode = "1f1e8-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1e6),
        TwemojiIcon(plainName = "CocosKeelingIslands", unicode = "1f1e8-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1e8),
        TwemojiIcon(plainName = "CongoKinshasa", unicode = "1f1e8-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1e9),
        TwemojiIcon(plainName = "CentralAfricanRepublic", unicode = "1f1e8-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1eb),
        TwemojiIcon(plainName = "CongoBrazzaville", unicode = "1f1e8-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1ec),
        TwemojiIcon(plainName = "Switzerland", unicode = "1f1e8-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1ed),
        TwemojiIcon(plainName = "CôteDIvoire", unicode = "1f1e8-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1ee),
        TwemojiIcon(plainName = "CookIslands", unicode = "1f1e8-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f0),
        TwemojiIcon(plainName = "Chile", unicode = "1f1e8-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f1),
        TwemojiIcon(plainName = "Cameroon", unicode = "1f1e8-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f2),
        TwemojiIcon(plainName = "China", unicode = "1f1e8-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f3),
        TwemojiIcon(plainName = "Colombia", unicode = "1f1e8-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f4),
        TwemojiIcon(plainName = "ClippertonIsland", unicode = "1f1e8-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f5),
        TwemojiIcon(plainName = "CostaRica", unicode = "1f1e8-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1f7),
        TwemojiIcon(plainName = "Cuba", unicode = "1f1e8-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1fa),
        TwemojiIcon(plainName = "CapeVerde", unicode = "1f1e8-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1fb),
        TwemojiIcon(plainName = "Curaçao", unicode = "1f1e8-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1fc),
        TwemojiIcon(plainName = "ChristmasIsland", unicode = "1f1e8-1f1fd", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1fd),
        TwemojiIcon(plainName = "Cyprus", unicode = "1f1e8-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1fe),
        TwemojiIcon(plainName = "Czechia", unicode = "1f1e8-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e8_1f1ff),
        TwemojiIcon(plainName = "Germany", unicode = "1f1e9-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1ea),
        TwemojiIcon(plainName = "DiegoGarcia", unicode = "1f1e9-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1ec),
        TwemojiIcon(plainName = "Djibouti", unicode = "1f1e9-1f1ef", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1ef),
        TwemojiIcon(plainName = "Denmark", unicode = "1f1e9-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1f0),
        TwemojiIcon(plainName = "Dominica", unicode = "1f1e9-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1f2),
        TwemojiIcon(plainName = "DominicanRepublic", unicode = "1f1e9-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1f4),
        TwemojiIcon(plainName = "Algeria", unicode = "1f1e9-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1e9_1f1ff),
        TwemojiIcon(plainName = "CeutaAndMelilla", unicode = "1f1ea-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1e6),
        TwemojiIcon(plainName = "Ecuador", unicode = "1f1ea-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1e8),
        TwemojiIcon(plainName = "Estonia", unicode = "1f1ea-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1ea),
        TwemojiIcon(plainName = "Egypt", unicode = "1f1ea-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1ec),
        TwemojiIcon(plainName = "WesternSahara", unicode = "1f1ea-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1ed),
        TwemojiIcon(plainName = "Eritrea", unicode = "1f1ea-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1f7),
        TwemojiIcon(plainName = "Spain", unicode = "1f1ea-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1f8),
        TwemojiIcon(plainName = "Ethiopia", unicode = "1f1ea-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1f9),
        TwemojiIcon(plainName = "EuropeanUnion", unicode = "1f1ea-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ea_1f1fa),
        TwemojiIcon(plainName = "Finland", unicode = "1f1eb-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1ee),
        TwemojiIcon(plainName = "Fiji", unicode = "1f1eb-1f1ef", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1ef),
        TwemojiIcon(plainName = "FalklandIslands", unicode = "1f1eb-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1f0),
        TwemojiIcon(plainName = "Micronesia", unicode = "1f1eb-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1f2),
        TwemojiIcon(plainName = "FaroeIslands", unicode = "1f1eb-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1f4),
        TwemojiIcon(plainName = "France", unicode = "1f1eb-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1eb_1f1f7),
        TwemojiIcon(plainName = "Gabon", unicode = "1f1ec-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1e6),
        TwemojiIcon(plainName = "UnitedKingdom", unicode = "1f1ec-1f1e7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1e7),
        TwemojiIcon(plainName = "Grenada", unicode = "1f1ec-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1e9),
        TwemojiIcon(plainName = "Georgia", unicode = "1f1ec-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1ea),
        TwemojiIcon(plainName = "FrenchGuiana", unicode = "1f1ec-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1eb),
        TwemojiIcon(plainName = "Guernsey", unicode = "1f1ec-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1ec),
        TwemojiIcon(plainName = "Ghana", unicode = "1f1ec-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1ed),
        TwemojiIcon(plainName = "Gibraltar", unicode = "1f1ec-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1ee),
        TwemojiIcon(plainName = "Greenland", unicode = "1f1ec-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f1),
        TwemojiIcon(plainName = "Gambia", unicode = "1f1ec-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f2),
        TwemojiIcon(plainName = "Guinea", unicode = "1f1ec-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f3),
        TwemojiIcon(plainName = "Guadeloupe", unicode = "1f1ec-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f5),
        TwemojiIcon(plainName = "EquatorialGuinea", unicode = "1f1ec-1f1f6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f6),
        TwemojiIcon(plainName = "Greece", unicode = "1f1ec-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f7),
        TwemojiIcon(plainName = "SouthGeorgiaAndSouthSandwichIslands", unicode = "1f1ec-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f8),
        TwemojiIcon(plainName = "Guatemala", unicode = "1f1ec-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1f9),
        TwemojiIcon(plainName = "Guam", unicode = "1f1ec-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1fa),
        TwemojiIcon(plainName = "GuineaBissau", unicode = "1f1ec-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1fc),
        TwemojiIcon(plainName = "Guyana", unicode = "1f1ec-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ec_1f1fe),
        TwemojiIcon(plainName = "HongKongSarChina", unicode = "1f1ed-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1f0),
        TwemojiIcon(plainName = "HeardAndMcdonaldIslands", unicode = "1f1ed-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1f2),
        TwemojiIcon(plainName = "Honduras", unicode = "1f1ed-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1f3),
        TwemojiIcon(plainName = "Croatia", unicode = "1f1ed-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1f7),
        TwemojiIcon(plainName = "Haiti", unicode = "1f1ed-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1f9),
        TwemojiIcon(plainName = "Hungary", unicode = "1f1ed-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ed_1f1fa),
        TwemojiIcon(plainName = "CanaryIslands", unicode = "1f1ee-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1e8),
        TwemojiIcon(plainName = "Indonesia", unicode = "1f1ee-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1e9),
        TwemojiIcon(plainName = "Ireland", unicode = "1f1ee-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1ea),
        TwemojiIcon(plainName = "Israel", unicode = "1f1ee-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f1),
        TwemojiIcon(plainName = "IsleOfMan", unicode = "1f1ee-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f2),
        TwemojiIcon(plainName = "India", unicode = "1f1ee-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f3),
        TwemojiIcon(plainName = "BritishIndianOceanTerritory", unicode = "1f1ee-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f4),
        TwemojiIcon(plainName = "Iraq", unicode = "1f1ee-1f1f6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f6),
        TwemojiIcon(plainName = "Iran", unicode = "1f1ee-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f7),
        TwemojiIcon(plainName = "Iceland", unicode = "1f1ee-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f8),
        TwemojiIcon(plainName = "Italy", unicode = "1f1ee-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ee_1f1f9),
        TwemojiIcon(plainName = "Jersey", unicode = "1f1ef-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ef_1f1ea),
        TwemojiIcon(plainName = "Jamaica", unicode = "1f1ef-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ef_1f1f2),
        TwemojiIcon(plainName = "Jordan", unicode = "1f1ef-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ef_1f1f4),
        TwemojiIcon(plainName = "Japan", unicode = "1f1ef-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ef_1f1f5),
        TwemojiIcon(plainName = "Kenya", unicode = "1f1f0-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1ea),
        TwemojiIcon(plainName = "Kyrgyzstan", unicode = "1f1f0-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1ec),
        TwemojiIcon(plainName = "Cambodia", unicode = "1f1f0-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1ed),
        TwemojiIcon(plainName = "Kiribati", unicode = "1f1f0-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1ee),
        TwemojiIcon(plainName = "Comoros", unicode = "1f1f0-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1f2),
        TwemojiIcon(plainName = "StKittsAndNevis", unicode = "1f1f0-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1f3),
        TwemojiIcon(plainName = "NorthKorea", unicode = "1f1f0-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1f5),
        TwemojiIcon(plainName = "SouthKorea", unicode = "1f1f0-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1f7),
        TwemojiIcon(plainName = "Kuwait", unicode = "1f1f0-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1fc),
        TwemojiIcon(plainName = "CaymanIslands", unicode = "1f1f0-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1fe),
        TwemojiIcon(plainName = "Kazakhstan", unicode = "1f1f0-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f0_1f1ff),
        TwemojiIcon(plainName = "Laos", unicode = "1f1f1-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1e6),
        TwemojiIcon(plainName = "Lebanon", unicode = "1f1f1-1f1e7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1e7),
        TwemojiIcon(plainName = "StLucia", unicode = "1f1f1-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1e8),
        TwemojiIcon(plainName = "Liechtenstein", unicode = "1f1f1-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1ee),
        TwemojiIcon(plainName = "SriLanka", unicode = "1f1f1-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1f0),
        TwemojiIcon(plainName = "Liberia", unicode = "1f1f1-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1f7),
        TwemojiIcon(plainName = "Lesotho", unicode = "1f1f1-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1f8),
        TwemojiIcon(plainName = "Lithuania", unicode = "1f1f1-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1f9),
        TwemojiIcon(plainName = "Luxembourg", unicode = "1f1f1-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1fa),
        TwemojiIcon(plainName = "Latvia", unicode = "1f1f1-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1fb),
        TwemojiIcon(plainName = "Libya", unicode = "1f1f1-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f1_1f1fe),
        TwemojiIcon(plainName = "Morocco", unicode = "1f1f2-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1e6),
        TwemojiIcon(plainName = "Monaco", unicode = "1f1f2-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1e8),
        TwemojiIcon(plainName = "Moldova", unicode = "1f1f2-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1e9),
        TwemojiIcon(plainName = "Montenegro", unicode = "1f1f2-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1ea),
        TwemojiIcon(plainName = "StMartin", unicode = "1f1f2-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1eb),
        TwemojiIcon(plainName = "Madagascar", unicode = "1f1f2-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1ec),
        TwemojiIcon(plainName = "MarshallIslands", unicode = "1f1f2-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1ed),
        TwemojiIcon(plainName = "NorthMacedonia", unicode = "1f1f2-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f0),
        TwemojiIcon(plainName = "Mali", unicode = "1f1f2-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f1),
        TwemojiIcon(plainName = "MyanmarBurma", unicode = "1f1f2-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f2),
        TwemojiIcon(plainName = "Mongolia", unicode = "1f1f2-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f3),
        TwemojiIcon(plainName = "MacaoSarChina", unicode = "1f1f2-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f4),
        TwemojiIcon(plainName = "NorthernMarianaIslands", unicode = "1f1f2-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f5),
        TwemojiIcon(plainName = "Martinique", unicode = "1f1f2-1f1f6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f6),
        TwemojiIcon(plainName = "Mauritania", unicode = "1f1f2-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f7),
        TwemojiIcon(plainName = "Montserrat", unicode = "1f1f2-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f8),
        TwemojiIcon(plainName = "Malta", unicode = "1f1f2-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1f9),
        TwemojiIcon(plainName = "Mauritius", unicode = "1f1f2-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1fa),
        TwemojiIcon(plainName = "Maldives", unicode = "1f1f2-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1fb),
        TwemojiIcon(plainName = "Malawi", unicode = "1f1f2-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1fc),
        TwemojiIcon(plainName = "Mexico", unicode = "1f1f2-1f1fd", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1fd),
        TwemojiIcon(plainName = "Malaysia", unicode = "1f1f2-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1fe),
        TwemojiIcon(plainName = "Mozambique", unicode = "1f1f2-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f2_1f1ff),
        TwemojiIcon(plainName = "Namibia", unicode = "1f1f3-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1e6),
        TwemojiIcon(plainName = "NewCaledonia", unicode = "1f1f3-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1e8),
        TwemojiIcon(plainName = "Niger", unicode = "1f1f3-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1ea),
        TwemojiIcon(plainName = "NorfolkIsland", unicode = "1f1f3-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1eb),
        TwemojiIcon(plainName = "Nigeria", unicode = "1f1f3-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1ec),
        TwemojiIcon(plainName = "Nicaragua", unicode = "1f1f3-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1ee),
        TwemojiIcon(plainName = "Netherlands", unicode = "1f1f3-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1f1),
        TwemojiIcon(plainName = "Norway", unicode = "1f1f3-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1f4),
        TwemojiIcon(plainName = "Nepal", unicode = "1f1f3-1f1f5", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1f5),
        TwemojiIcon(plainName = "Nauru", unicode = "1f1f3-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1f7),
        TwemojiIcon(plainName = "Niue", unicode = "1f1f3-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1fa),
        TwemojiIcon(plainName = "NewZealand", unicode = "1f1f3-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f3_1f1ff),
        TwemojiIcon(plainName = "Oman", unicode = "1f1f4-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f4_1f1f2),
        TwemojiIcon(plainName = "Panama", unicode = "1f1f5-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1e6),
        TwemojiIcon(plainName = "Peru", unicode = "1f1f5-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1ea),
        TwemojiIcon(plainName = "FrenchPolynesia", unicode = "1f1f5-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1eb),
        TwemojiIcon(plainName = "PapuaNewGuinea", unicode = "1f1f5-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1ec),
        TwemojiIcon(plainName = "Philippines", unicode = "1f1f5-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1ed),
        TwemojiIcon(plainName = "Pakistan", unicode = "1f1f5-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f0),
        TwemojiIcon(plainName = "Poland", unicode = "1f1f5-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f1),
        TwemojiIcon(plainName = "StPierreAndMiquelon", unicode = "1f1f5-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f2),
        TwemojiIcon(plainName = "PitcairnIslands", unicode = "1f1f5-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f3),
        TwemojiIcon(plainName = "PuertoRico", unicode = "1f1f5-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f7),
        TwemojiIcon(plainName = "PalestinianTerritories", unicode = "1f1f5-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f8),
        TwemojiIcon(plainName = "Portugal", unicode = "1f1f5-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1f9),
        TwemojiIcon(plainName = "Palau", unicode = "1f1f5-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1fc),
        TwemojiIcon(plainName = "Paraguay", unicode = "1f1f5-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f5_1f1fe),
        TwemojiIcon(plainName = "Qatar", unicode = "1f1f6-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f6_1f1e6),
        TwemojiIcon(plainName = "Réunion", unicode = "1f1f7-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f7_1f1ea),
        TwemojiIcon(plainName = "Romania", unicode = "1f1f7-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f7_1f1f4),
        TwemojiIcon(plainName = "Serbia", unicode = "1f1f7-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f7_1f1f8),
        TwemojiIcon(plainName = "Russia", unicode = "1f1f7-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f7_1f1fa),
        TwemojiIcon(plainName = "Rwanda", unicode = "1f1f7-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f7_1f1fc),
        TwemojiIcon(plainName = "SaudiArabia", unicode = "1f1f8-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1e6),
        TwemojiIcon(plainName = "SolomonIslands", unicode = "1f1f8-1f1e7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1e7),
        TwemojiIcon(plainName = "Seychelles", unicode = "1f1f8-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1e8),
        TwemojiIcon(plainName = "Sudan", unicode = "1f1f8-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1e9),
        TwemojiIcon(plainName = "Sweden", unicode = "1f1f8-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ea),
        TwemojiIcon(plainName = "Singapore", unicode = "1f1f8-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ec),
        TwemojiIcon(plainName = "StHelena", unicode = "1f1f8-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ed),
        TwemojiIcon(plainName = "Slovenia", unicode = "1f1f8-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ee),
        TwemojiIcon(plainName = "SvalbardAndJanMayen", unicode = "1f1f8-1f1ef", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ef),
        TwemojiIcon(plainName = "Slovakia", unicode = "1f1f8-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f0),
        TwemojiIcon(plainName = "SierraLeone", unicode = "1f1f8-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f1),
        TwemojiIcon(plainName = "SanMarino", unicode = "1f1f8-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f2),
        TwemojiIcon(plainName = "Senegal", unicode = "1f1f8-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f3),
        TwemojiIcon(plainName = "Somalia", unicode = "1f1f8-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f4),
        TwemojiIcon(plainName = "Suriname", unicode = "1f1f8-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f7),
        TwemojiIcon(plainName = "SouthSudan", unicode = "1f1f8-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f8),
        TwemojiIcon(plainName = "SãoToméAndPríncipe", unicode = "1f1f8-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1f9),
        TwemojiIcon(plainName = "ElSalvador", unicode = "1f1f8-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1fb),
        TwemojiIcon(plainName = "SintMaarten", unicode = "1f1f8-1f1fd", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1fd),
        TwemojiIcon(plainName = "Syria", unicode = "1f1f8-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1fe),
        TwemojiIcon(plainName = "Eswatini", unicode = "1f1f8-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f8_1f1ff),
        TwemojiIcon(plainName = "TristanDaCunha", unicode = "1f1f9-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1e6),
        TwemojiIcon(plainName = "TurksAndCaicosIslands", unicode = "1f1f9-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1e8),
        TwemojiIcon(plainName = "Chad", unicode = "1f1f9-1f1e9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1e9),
        TwemojiIcon(plainName = "FrenchSouthernTerritories", unicode = "1f1f9-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1eb),
        TwemojiIcon(plainName = "Togo", unicode = "1f1f9-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1ec),
        TwemojiIcon(plainName = "Thailand", unicode = "1f1f9-1f1ed", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1ed),
        TwemojiIcon(plainName = "Tajikistan", unicode = "1f1f9-1f1ef", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1ef),
        TwemojiIcon(plainName = "Tokelau", unicode = "1f1f9-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f0),
        TwemojiIcon(plainName = "TimorLeste", unicode = "1f1f9-1f1f1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f1),
        TwemojiIcon(plainName = "Turkmenistan", unicode = "1f1f9-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f2),
        TwemojiIcon(plainName = "Tunisia", unicode = "1f1f9-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f3),
        TwemojiIcon(plainName = "Tonga", unicode = "1f1f9-1f1f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f4),
        TwemojiIcon(plainName = "Turkey", unicode = "1f1f9-1f1f7", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f7),
        TwemojiIcon(plainName = "TrinidadAndTobago", unicode = "1f1f9-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1f9),
        TwemojiIcon(plainName = "Tuvalu", unicode = "1f1f9-1f1fb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1fb),
        TwemojiIcon(plainName = "Taiwan", unicode = "1f1f9-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1fc),
        TwemojiIcon(plainName = "Tanzania", unicode = "1f1f9-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1f9_1f1ff),
        TwemojiIcon(plainName = "Ukraine", unicode = "1f1fa-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1e6),
        TwemojiIcon(plainName = "Uganda", unicode = "1f1fa-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1ec),
        TwemojiIcon(plainName = "USOutlyingIslands", unicode = "1f1fa-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1f2),
        TwemojiIcon(plainName = "UnitedStates", unicode = "1f1fa-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1f8),
        TwemojiIcon(plainName = "Uruguay", unicode = "1f1fa-1f1fe", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1fe),
        TwemojiIcon(plainName = "Uzbekistan", unicode = "1f1fa-1f1ff", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1ff),
        TwemojiIcon(plainName = "VaticanCity", unicode = "1f1fb-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1e6),
        TwemojiIcon(plainName = "StVincentAndGrenadines", unicode = "1f1fb-1f1e8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1e8),
        TwemojiIcon(plainName = "Venezuela", unicode = "1f1fb-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1ea),
        TwemojiIcon(plainName = "BritishVirginIslands", unicode = "1f1fb-1f1ec", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1ec),
        TwemojiIcon(plainName = "USVirginIslands", unicode = "1f1fb-1f1ee", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1ee),
        TwemojiIcon(plainName = "Vietnam", unicode = "1f1fb-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1f3),
        TwemojiIcon(plainName = "Vanuatu", unicode = "1f1fb-1f1fa", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fb_1f1fa),
        TwemojiIcon(plainName = "WallisAndFutuna", unicode = "1f1fc-1f1eb", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fc_1f1eb),
        TwemojiIcon(plainName = "Samoa", unicode = "1f1fc-1f1f8", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fc_1f1f8),
        TwemojiIcon(plainName = "Kosovo", unicode = "1f1fd-1f1f0", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fd_1f1f0),
        TwemojiIcon(plainName = "Yemen", unicode = "1f1fe-1f1ea", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fe_1f1ea),
        TwemojiIcon(plainName = "Mayotte", unicode = "1f1fe-1f1f9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fe_1f1f9),
        TwemojiIcon(plainName = "SouthAfrica", unicode = "1f1ff-1f1e6", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ff_1f1e6),
        TwemojiIcon(plainName = "Zambia", unicode = "1f1ff-1f1f2", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ff_1f1f2),
        TwemojiIcon(plainName = "Zimbabwe", unicode = "1f1ff-1f1fc", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1ff_1f1fc),
        TwemojiIcon(plainName = "UnitedNations", unicode = "1f1fa-1f1f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.CountryFlag, resource = R.drawable.ic_1f1fa_1f1f3)
    )
    // endrgion

    // region Other
    fun provideOthers() = listOf(
        TwemojiIcon(plainName = "ChequeredFlag", unicode = "1f3c1", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3c1),
        TwemojiIcon(plainName = "TriangularFlag", unicode = "1f6a9", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f6a9),
        TwemojiIcon(plainName = "CrossedFlags", unicode = "1f38c", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f38c),
        TwemojiIcon(plainName = "BlackFlag", unicode = "1f3f4", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3f4),
        TwemojiIcon(plainName = "WhiteFlag", unicode = "1f3f3", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3f3),
        TwemojiIcon(plainName = "RainbowFlag", unicode = "1f3f3-fe0f-200d-1f308", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3f3_fe0f_200d_1f308),
        TwemojiIcon(plainName = "PirateFlag", unicode = "1f3f4-200d-2620-fe0f", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3f4_200d_2620_fe0f),
        TwemojiIcon(plainName = "TransgenderFlag", unicode = "1f3f3-fe0f-200d-26a7-fe0f", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.Flag, resource = R.drawable.ic_1f3f3_fe0f_200d_26a7_fe0f)
    )
    // endregion

    // region Subdivision flags
    fun provideSubdivisionFlags() = listOf(
        TwemojiIcon(plainName = "England", unicode = "1f3f4-e0067-e0062-e0065-e006e-e0067-e007f", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.SubdivisionFlag, resource = R.drawable.ic_1f3f4_e0067_e0062_e0065_e006e_e0067_e007f),
        TwemojiIcon(plainName = "Scotland", unicode = "1f3f4-e0067-e0062-e0073-e0063-e0074-e007f", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.SubdivisionFlag, resource = R.drawable.ic_1f3f4_e0067_e0062_e0073_e0063_e0074_e007f),
        TwemojiIcon(plainName = "Wales", unicode = "1f3f4-e0067-e0062-e0077-e006c-e0073-e007f", category = TwemojiCategory.Flags, subcategory = TwemojiSubcategory.SubdivisionFlag, resource = R.drawable.ic_1f3f4_e0067_e0062_e0077_e006c_e0073_e007f)
    )
    // endregion

}