package no.mhl.twemojiiconsandroid

import androidx.annotation.DrawableRes

data class TwemojiIcon(
    val plainName: String,
    val unicode: String,
    val category: TwemojiCategory,
    val subcategory: TwemojiSubcategory,
    @DrawableRes val resource: Int
)

enum class TwemojiIconnn(
    val plainName: String,
    val unicode: String,
    val category: TwemojiCategory,
    val subcategory: TwemojiSubcategory,
    @DrawableRes val resource: Int
) {

    /**
     * Symbols
     */
    // region Alphanum
    OkButton(plainName = "OkButton", unicode = "1f197", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f197),
    SosButton(plainName = "SosButton", unicode = "1f198", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f198),
    CoolButton(plainName = "CoolButton", unicode = "1f192", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f192),
    UpButton(plainName = "UpButton", unicode = "1f199", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f199),
    NewButton(plainName = "NewButton", unicode = "1f195", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f195),
    FreeButton(plainName = "FreeButton", unicode = "1f193", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f193),
    AButtonBloodType(plainName = "AButtonBloodType", unicode = "1f170", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f170),
    JapaneseDiscountButton(plainName = "JapaneseDiscountButton", unicode = "1f239", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f239),
    BButtonBloodType(plainName = "BButtonBloodType", unicode = "1f171", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f171),
    CircledM(plainName = "CircledM", unicode = "24c2", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_24c2),
    OButtonBloodType(plainName = "OButtonBloodType", unicode = "1f17e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f17e),
    IdButton(plainName = "IdButton", unicode = "1f194", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f194),
    JapaneseSecretButton(plainName = "JapaneseSecretButton", unicode = "3299", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_3299),
    JapaneseCongratulationsButton(plainName = "JapaneseCongratulationsButton", unicode = "3297", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_3297),
    Information(plainName = "Information", unicode = "2139", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_2139),
    VsButton(plainName = "VsButton", unicode = "1f19a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f19a),
    PButton(plainName = "PButton", unicode = "1f17f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f17f),
    JapaneseBargainButton(plainName = "JapaneseBargainButton", unicode = "1f250", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f250),
    NgButton(plainName = "NgButton", unicode = "1f196", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f196),
    JapaneseVacancyButton(plainName = "JapaneseVacancyButton", unicode = "1f233", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f233),
    AbButtonBloodType(plainName = "AbButtonBloodType", unicode = "1f18e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f18e),
    ClButton(plainName = "ClButton", unicode = "1f191", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f191),
    JapaneseOpenForBusinessButton(plainName = "JapaneseOpenForBusinessButton", unicode = "1f23a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f23a),
    JapaneseNotFreeOfChargeButton(plainName = "JapaneseNotFreeOfChargeButton", unicode = "1f236", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f236),
    JapaneseApplicationButton(plainName = "JapaneseApplicationButton", unicode = "1f238", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f238),
    JapaneseMonthlyAmountButton(plainName = "JapaneseMonthlyAmountButton", unicode = "1f237", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f237),
    InputNumbers(plainName = "InputNumbers", unicode = "1f522", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f522),
    JapaneseProhibitedButton(plainName = "JapaneseProhibitedButton", unicode = "1f232", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f232),
    JapaneseNoVacancyButton(plainName = "JapaneseNoVacancyButton", unicode = "1f235", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f235),
    JapaneseAcceptableButton(plainName = "JapaneseAcceptableButton", unicode = "1f251", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f251),
    JapanesePassingGradeButton(plainName = "JapanesePassingGradeButton", unicode = "1f234", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f234),
    JapaneseServiceChargeButton(plainName = "JapaneseServiceChargeButton", unicode = "1f202", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f202),
    InputLatinLetters(plainName = "InputLatinLetters", unicode = "1f524", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f524),
    InputLatinUppercase(plainName = "InputLatinUppercase", unicode = "1f520", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f520),
    InputSymbols(plainName = "InputSymbols", unicode = "1f523", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f523),
    InputLatinLowercase(plainName = "InputLatinLowercase", unicode = "1f521", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f521),
    JapaneseHereButton(plainName = "JapaneseHereButton", unicode = "1f201", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f201),
    JapaneseReservedButton(plainName = "JapaneseReservedButton", unicode = "1f22f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f22f),
    JapaneseFreeOfChargeButton(plainName = "JapaneseFreeOfChargeButton", unicode = "1f21a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Alphanum, resource = R.drawable.ic_1f21a),
    // endregion

    // region Av
    PlayButton(plainName = "PlayButton", unicode = "25b6", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_25b6),
    ReverseButton(plainName = "ReverseButton", unicode = "25c0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_25c0),
    FastForwardButton(plainName = "FastForwardButton", unicode = "23e9", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23e9),
    RepeatButton(plainName = "RepeatButton", unicode = "1f501", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f501),
    FastReverseButton(plainName = "FastReverseButton", unicode = "23ea", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23ea),
    BrightButton(plainName = "BrightButton", unicode = "1f506", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f506),
    UpwardsButton(plainName = "UpwardsButton", unicode = "1f53c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f53c),
    MobilePhoneOff(plainName = "MobilePhoneOff", unicode = "1f4f4", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f4f4),
    FastUpButton(plainName = "FastUpButton", unicode = "23eb", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23eb),
    AntennaBars(plainName = "AntennaBars", unicode = "1f4f6", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f4f6),
    DimButton(plainName = "DimButton", unicode = "1f505", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f505),
    FastDownButton(plainName = "FastDownButton", unicode = "23ec", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23ec),
    DownwardsButton(plainName = "DownwardsButton", unicode = "1f53d", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f53d),
    Cinema(plainName = "Cinema", unicode = "1f3a6", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f3a6),
    RepeatSingleButton(plainName = "RepeatSingleButton", unicode = "1f502", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f502),
    VibrationMode(plainName = "VibrationMode", unicode = "1f4f3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f4f3),
    ShuffleTracksButton(plainName = "ShuffleTracksButton", unicode = "1f500", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_1f500),
    RecordButton(plainName = "RecordButton", unicode = "23fa", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23fa),
    StopButton(plainName = "StopButton", unicode = "23f9", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23f9),
    PauseButton(plainName = "PauseButton", unicode = "23f8", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23f8),
    PlayOrPauseButton(plainName = "PlayOrPauseButton", unicode = "23ef", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23ef),
    LastTrackButton(plainName = "LastTrackButton", unicode = "23ee", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23ee),
    NextTrackButton(plainName = "NextTrackButton", unicode = "23ed", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23ed),
    EjectButton(plainName = "EjectButton", unicode = "23cf", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.AvSymbol, resource = R.drawable.ic_23cf),
    // endregion

    // region Gender
    FemaleSign(plainName = "FemaleSign", unicode = "2640", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Gender, resource = R.drawable.ic_2640),
    MaleSign(plainName = "MaleSign", unicode = "2642", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Gender, resource = R.drawable.ic_2642),
    // endregion

    // region Geometric
    RedCircle(plainName = "RedCircle", unicode = "1f534", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f534),
    SmallOrangeDiamond(plainName = "SmallOrangeDiamond", unicode = "1f538", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f538),
    BlackSmallSquare(plainName = "BlackSmallSquare", unicode = "25aa", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25aa),
    BlueCircle(plainName = "BlueCircle", unicode = "1f535", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f535),
    BlackCircle(plainName = "BlackCircle", unicode = "26ab", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_26ab),
    WhiteCircle(plainName = "WhiteCircle", unicode = "26aa", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_26aa),
    SmallBlueDiamond(plainName = "SmallBlueDiamond", unicode = "1f539", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f539),
    RadioButton(plainName = "RadioButton", unicode = "1f518", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f518),
    RedTrianglePointedUp(plainName = "RedTrianglePointedUp", unicode = "1f53a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f53a),
    RedTrianglePointedDown(plainName = "RedTrianglePointedDown", unicode = "1f53b", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f53b),
    DiamondWithADot(plainName = "DiamondWithADot", unicode = "1f4a0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f4a0),
    LargeBlueDiamond(plainName = "LargeBlueDiamond", unicode = "1f537", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f537),
    LargeOrangeDiamond(plainName = "LargeOrangeDiamond", unicode = "1f536", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f536),
    BlackSquareButton(plainName = "BlackSquareButton", unicode = "1f532", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f532),
    WhiteSquareButton(plainName = "WhiteSquareButton", unicode = "1f533", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f533),
    BlackMediumSmallSquare(plainName = "BlackMediumSmallSquare", unicode = "25fe", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25fe),
    WhiteSmallSquare(plainName = "WhiteSmallSquare", unicode = "25ab", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25ab),
    BlackMediumSquare(plainName = "BlackMediumSquare", unicode = "25fc", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25fc),
    WhiteLargeSquare(plainName = "WhiteLargeSquare", unicode = "2b1c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_2b1c),
    WhiteMediumSquare(plainName = "WhiteMediumSquare", unicode = "25fb", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25fb),
    BlackLargeSquare(plainName = "BlackLargeSquare", unicode = "2b1b", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_2b1b),
    WhiteMediumSmallSquare(plainName = "WhiteMediumSmallSquare", unicode = "25fd", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_25fd),
    OrangeCircle(plainName = "OrangeCircle", unicode = "1f7e0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e0),
    YellowCircle(plainName = "YellowCircle", unicode = "1f7e1", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e1),
    GreenCircle(plainName = "GreenCircle", unicode = "1f7e2", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e2),
    PurpleCircle(plainName = "PurpleCircle", unicode = "1f7e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e3),
    BrownCircle(plainName = "BrownCircle", unicode = "1f7e4", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e4),
    RedSquare(plainName = "RedSquare", unicode = "1f7e5", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e5),
    OrangeSquare(plainName = "OrangeSquare", unicode = "1f7e7", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e7),
    YellowSquare(plainName = "YellowSquare", unicode = "1f7e8", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e8),
    GreenSquare(plainName = "GreenSquare", unicode = "1f7e9", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e9),
    BlueSquare(plainName = "BlueSquare", unicode = "1f7e6", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Geometric, resource = R.drawable.ic_1f7e6),
    // endregion

    // region Keycap
    Keycap10(plainName = "Keycap10", unicode = "1f51f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_1f51f),
    KeycapNumber(plainName = "KeycapNumber", unicode = "23-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_23_20e3),
    Keycap0(plainName = "Keycap0", unicode = "30-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_30_20e3),
    Keycap1(plainName = "Keycap1", unicode = "31-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_31_20e3),
    Keycap2(plainName = "Keycap2", unicode = "32-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_32_20e3),
    Keycap3(plainName = "Keycap3", unicode = "33-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_33_20e3),
    Keycap4(plainName = "Keycap4", unicode = "34-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_34_20e3),
    Keycap5(plainName = "Keycap5", unicode = "35-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_35_20e3),
    Keycap6(plainName = "Keycap6", unicode = "36-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_36_20e3),
    Keycap7(plainName = "Keycap7", unicode = "37-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_37_20e3),
    Keycap8(plainName = "Keycap8", unicode = "38-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_38_20e3),
    Keycap9(plainName = "Keycap9", unicode = "39-20e3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Keycap, resource = R.drawable.ic_39_20e3),
    // endregion

    // region Other
    RecyclingSymbol(plainName = "RecyclingSymbol", unicode = "267b", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_267b),
    CheckMark(plainName = "CheckMark", unicode = "2714", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2714),
    CheckMarkButton(plainName = "CheckMarkButton", unicode = "2705", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2705),
    CheckBoxWithCheck(plainName = "CheckBoxWithCheck", unicode = "2611", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2611),
    DoubleExclamationMark(plainName = "DoubleExclamationMark", unicode = "203c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_203c),
    CrossMark(plainName = "CrossMark", unicode = "274c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_274c),
    ExclamationMark(plainName = "ExclamationMark", unicode = "2757", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2757),
    MultiplicationSign(plainName = "MultiplicationSign", unicode = "2716", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2716),
    HollowRedCircle(plainName = "HollowRedCircle", unicode = "2b55", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2b55),
    QuestionMark(plainName = "QuestionMark", unicode = "2753", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2753),
    EightSpokedAsterisk(plainName = "EightSpokedAsterisk", unicode = "2733", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2733),
    WhiteExclamationMark(plainName = "WhiteExclamationMark", unicode = "2755", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2755),
    ExclamationQuestionMark(plainName = "ExclamationQuestionMark", unicode = "2049", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2049),
    TridentEmblem(plainName = "TridentEmblem", unicode = "1f531", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_1f531),
    CurlyLoop(plainName = "CurlyLoop", unicode = "27b0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_27b0),
    WavyDash(plainName = "WavyDash", unicode = "3030", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_3030),
    EightPointedStar(plainName = "EightPointedStar", unicode = "2734", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2734),
    PlusSign(plainName = "PlusSign", unicode = "2795", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2795),
    NameBadge(plainName = "NameBadge", unicode = "1f4db", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_1f4db),
    Sparkle(plainName = "Sparkle", unicode = "2747", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2747),
    MinusSign(plainName = "MinusSign", unicode = "2796", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2796),
    PartAlternationMark(plainName = "PartAlternationMark", unicode = "303d", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_303d),
    CrossMarkButton(plainName = "CrossMarkButton", unicode = "274e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_274e),
    WhiteQuestionMark(plainName = "WhiteQuestionMark", unicode = "2754", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2754),
    JapaneseSymbolForBeginner(plainName = "JapaneseSymbolForBeginner", unicode = "1f530", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_1f530),
    DoubleCurlyLoop(plainName = "DoubleCurlyLoop", unicode = "27bf", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_27bf),
    DivisionSign(plainName = "DivisionSign", unicode = "2797", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2797),
    FleurDeLis(plainName = "FleurDeLis", unicode = "269c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_269c),
    TradeMark(plainName = "TradeMark", unicode = "2122", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2122),
    MedicalSymbol(plainName = "MedicalSymbol", unicode = "2695", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_2695),
    Infinity(plainName = "Infinity", unicode = "267e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.OtherSymbol, resource = R.drawable.ic_267e),
    // endregion

    // region Religion
    DottedSixPointedStar(plainName = "DottedSixPointedStar", unicode = "1f52f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_1f52f),
    StarOfDavid(plainName = "StarOfDavid", unicode = "2721", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_2721),
    LatinCross(plainName = "LatinCross", unicode = "271d", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_271d),
    AtomSymbol(plainName = "AtomSymbol", unicode = "269b", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_269b),
    WheelOfDharma(plainName = "WheelOfDharma", unicode = "2638", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_2638),
    YinYang(plainName = "YinYang", unicode = "262f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_262f),
    PeaceSymbol(plainName = "PeaceSymbol", unicode = "262e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_262e),
    StarAndCrescent(plainName = "StarAndCrescent", unicode = "262a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_262a),
    OrthodoxCross(plainName = "OrthodoxCross", unicode = "2626", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_2626),
    PlaceOfWorship(plainName = "PlaceOfWorship", unicode = "1f6d0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_1f6d0),
    Menorah(plainName = "Menorah", unicode = "1f54e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_1f54e),
    Om(plainName = "Om", unicode = "1f549", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Religion, resource = R.drawable.ic_1f549),
    // endregion

    // region Transport Sign
    LitterInBinSign(plainName = "LitterInBinSign", unicode = "1f6ae", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6ae),
    LeftLuggage(plainName = "LeftLuggage", unicode = "1f6c5", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6c5),
    Customs(plainName = "Customs", unicode = "1f6c3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6c3),
    BabySymbol(plainName = "BabySymbol", unicode = "1f6bc", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6bc),
    WomenSRoom(plainName = "WomenSRoom", unicode = "1f6ba", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6ba),
    MenSRoom(plainName = "MenSRoom", unicode = "1f6b9", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6b9),
    WheelchairSymbol(plainName = "WheelchairSymbol", unicode = "267f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_267f),
    AtmSign(plainName = "AtmSign", unicode = "1f3e7", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f3e7),
    WaterCloset(plainName = "WaterCloset", unicode = "1f6be", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6be),
    Restroom(plainName = "Restroom", unicode = "1f6bb", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6bb),
    PotableWater(plainName = "PotableWater", unicode = "1f6b0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6b0),
    PassportControl(plainName = "PassportControl", unicode = "1f6c2", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6c2),
    BaggageClaim(plainName = "BaggageClaim", unicode = "1f6c4", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.TransportSign, resource = R.drawable.ic_1f6c4),
    // endregion

    // region Warning
    NoOneUnderEighteen(plainName = "NoOneUnderEighteen", unicode = "1f51e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f51e),
    Warning(plainName = "Warning", unicode = "26a0", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_26a0),
    Prohibited(plainName = "Prohibited", unicode = "1f6ab", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6ab),
    NoEntry(plainName = "NoEntry", unicode = "26d4", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_26d4),
    NoMobilePhones(plainName = "NoMobilePhones", unicode = "1f4f5", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f4f5),
    NoSmoking(plainName = "NoSmoking", unicode = "1f6ad", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6ad),
    NoPedestrians(plainName = "NoPedestrians", unicode = "1f6b7", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6b7),
    ChildrenCrossing(plainName = "ChildrenCrossing", unicode = "1f6b8", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6b8),
    NoLittering(plainName = "NoLittering", unicode = "1f6af", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6af),
    NonPotableWater(plainName = "NonPotableWater", unicode = "1f6b1", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6b1),
    NoBicycles(plainName = "NoBicycles", unicode = "1f6b3", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_1f6b3),
    Biohazard(plainName = "Biohazard", unicode = "2623", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_2623),
    Radioactive(plainName = "Radioactive", unicode = "2622", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Warning, resource = R.drawable.ic_2622),
    // endregion

    // region Zodiac
    Cancer(plainName = "Cancer", unicode = "264b", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264b),
    Aquarius(plainName = "Aquarius", unicode = "2652", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2652),
    Aries(plainName = "Aries", unicode = "2648", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2648),
    Scorpio(plainName = "Scorpio", unicode = "264f", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264f),
    Sagittarius(plainName = "Sagittarius", unicode = "2650", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2650),
    Leo(plainName = "Leo", unicode = "264c", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264c),
    Gemini(plainName = "Gemini", unicode = "264a", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264a),
    Taurus(plainName = "Taurus", unicode = "2649", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2649),
    Pisces(plainName = "Pisces", unicode = "2653", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2653),
    Capricorn(plainName = "Capricorn", unicode = "2651", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_2651),
    Libra(plainName = "Libra", unicode = "264e", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264e),
    Virgo(plainName = "Virgo", unicode = "264d", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_264d),
    Ophiuchus(plainName = "Ophiuchus", unicode = "26ce", category = TwemojiCategory.Symbols, subcategory = TwemojiSubcategory.Zodiac, resource = R.drawable.ic_26ce),
    // endregion

}
